### ISSUE TITLE
How to install Citrus on a Mac or PC

### ISSUE THREAD

**Issue by MorganSimoneS** [nolanlab/citrus#115]
Has anyone been experiencing issues with installing Citrus on a Mac or PC? I have tried both and used the following code chunk. However, R Studio keeps saying there is an error. Any advice would be helpful I have also installed all the necessary package such as X code on Mac and the R tools package for PC

install.packages("glmnet")
install.packages("pamr") 
install.packages("ggplot2")
install.packages("survival")
source("http://bioconductor.org/biocLite.R")
biocLite("flowCore")
biocLite("impute")
install.packages("samr")

**Comment by rbruggner** [comment]
Can you post error messages please?

**Comment by MorganSimoneS** [comment]
<img width="1273" alt="screen shot 2018-02-23 at 2 11 54 pm" src="https://user-images.githubusercontent.com/36487278/36612130-a6f66a7a-18a3-11e8-8182-fe75d37d3fd2.png">

This is the error message I am getting which is strange because in the past ggplot2 normally works fine

**Comment by rbruggner** [comment]
According to the messages that you're posting, it doesn't seem that the Citrus package is installed. Have you installed it?

**Comment by SamGG** [comment]
It seems you are trying to install ggplot2 although it is already installed, as shown on the bottom right panel. To start a citrus session once installed, you only need the two commands of the last chunk.
If you really want to install citrus again, the best is to start from the beginning. Close ALL the RStudio sessions and R terminals if any. Then try again. It looks quite odd to me that you put those commands in a Markdown document because there is no interest in formatting their output, but it should run. HTH.

**Comment by MorganSimoneS** [comment]
I have installed it several times and it still won't work which is incredibly strange. Any installation tips?

**Comment by MorganSimoneS** [comment]
No matter what I try I can't install Citrus today I tried on a PC and got the following message 
![screenshot 1](https://user-images.githubusercontent.com/36487278/36811223-08c30678-1c9b-11e8-8063-186769af8ad1.png)

**Comment by bc2zb** [comment]
Try using 

devtools::install_github instead

When R indicates it cannot find a function, it usually means you haven't loaded the library. Using the [library]::[function] tells R explicitly which library and function to use. This is very useful if you are using libraries that have identically named functions. FlowCore::filter and dplyr::filter being two obnoxious examples I run into constantly.

**Comment by MorganSimoneS** [comment]
Awesome thank you I will try that now and let you know if it works

**Comment by MorganSimoneS** [comment]
@bc2zb 
Just tried it and R still is saying there is no package called devtools

**Comment by bc2zb** [comment]
Try reinstalling devtools then.

**Comment by MorganSimoneS** [comment]
I just reinstalled and it worked, I am attempting to call Citrus and use it

**Comment by MorganSimoneS** [comment]
Never mind
![screenshot 2](https://user-images.githubusercontent.com/36487278/36811840-2e2ed4e4-1c9d-11e8-85aa-f794769bf2ac.png)
 I am still screwed

**Comment by bc2zb** [comment]
````
library(devtools)
install_github("nolanlab/Rcluserpp")
install_github("nolanlab/citrus")
````
If all of that goes through with no errors (look at the terminal output), then try library(citrus).

**Comment by rbruggner** [comment]
@MorganSimoneS the issues you're posting are general issues related to using R, not issues related to Citrus. Do you have a co-worker who is familiar with R in general (not necessarily with citrus) who can help you with the installation issues?

**Comment by SamGG** [comment]
I think you are trying to install all the libraries at once by running the whole chunk. If so, I would advise you to run one line at a time, and to check each library is correctly installed before issuing the next library installation: just call 'library(<the_library_you_have_just_installed>)' to check that no error occurs.
In the log on your screenshot, it looks like the packages are download and ready to install, but it seems that an error occurs and blocks the end of the installation. That's why I recommend a slow line by line installation. Don't hesitate to close all R or RStudio sessions and restart where the installation fails. Hope this help.

**Comment by MorganSimoneS** [comment]
I have been successful this go around however apparently the version of R I am using is not compatible with Citrus. I also ran each code line by line and uninstalled and reinstalled again to reach this point. Which version is correct?
![r issues](https://user-images.githubusercontent.com/36487278/36916955-72cc0dce-1e23-11e8-846c-74890627aa9a.png)

**Comment by SamGG** [comment]
Your error is quite obvious: the only way to install citrus is via install.github(), not by install.packages() nor bioclite(). Please, read carefully the instructions, understand every single line of code, and if there is an error, breath and try to understand what's going on. I will recommend you to ask help around you.
