### ISSUE TITLE
Citrus GUI not recognizing commands

### ISSUE THREAD

**Issue by horowitzamir** [nolanlab/citrus#61]
I have a dataset that I am analyzing in Citrus. In the GUI, there are multiple areas where upon clicking to highlight/activate, the field is not checked. For example, I wanted to analyze medians. I could click on that feature but was unable to select any of the markers that appear below. This is happening in other areas as well.
Thanks for looking into this.

**Comment by cjla87** [comment]
Hi Rob,

Hope all is well. I'm writing because I am having the same issue that Amir describes here. I tried running the fix: 
update.packages()
library("devtools")
install_github("citrus","nolanlab",ref="uiUpdate")

but I get the following error:

ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [citrus.so] Error 1
ERROR: compilation failed for package ‘citrus’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/citrus’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/citrus’
Error: Command failed (1)

Thoughts on how to resolve this? Thanks for your help!
